name: Build and Push Docker Image


on:
  push:
    branches:
    - main


jobs:
  build:
    
    #permissions:
    #  contents: read
    #  id-token: write
      
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      run: |
        docker-compose build
        docker-compose push
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    #- name: Azure login
    #  uses: azure/login@v1.4.6
    #  with:
    #    client-id: ${{ secrets.AZURE_CLIENT_ID }}
    #    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
       
    - name: Set up AKS context
      uses: azure/aks-set-context@v1
      with:
        #client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: attendance-system-k8s
        resource-group: Attendance-System-RG
       
    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          Deployment_Scripts/deployment.yaml
          Deployment_Scripts/service.yaml
        images: |
          image: nikbik/eureka_server_image:latest